language: python
python:
  - "3.5"

install:
  - pip install coverage coveralls codecov tox
script:
  - tox
after_success:
  - coveralls
  - codecov

env:
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=isort
  # - TOXENV=docs
